### ISSUE TITLE
v1.5.0 - Blank page when displaying any Form

### ISSUE THREAD

**Issue by AlePini** [cioraneanu/firefly-pico#137]
Hi, I'm trying Firefly III and I found your project as a nice mobile interface.

But since I upgraded from 1.4.2 to 1.5.0 all pages that contains a form (such as new/edit transaction) display blank with following error:
`TypeError: crypto.randomUUID is not a function`
![immagine](https://github.com/user-attachments/assets/f617e38e-095e-4ca9-9037-fe9d5a08d6a8)

I tried with different browser, such as Brave, Vivaldi, Chrome, Firefox but the error persist.
I think the culprit is the commit 4b4c3d3

**Comment by cioraneanu** [comment]
You are right, crypto.randomUUID is not available if you serve the app over http but works if you use https.

Using the `dev` docker tag should fix it :)

**Comment by cioraneanu** [comment]
Update `latest` tag as well

**Comment by AlePini** [comment]
Confirm that now it's working as inteded!

Thanks so much for fixing this bug so quickly :D
